### PR TITLE
New Decisions doc; miscellaneous other changes

### PR DESCRIPTION
**Pull request by CharliePoole**
Please review. I have attempted to make specific those aspects of decision-making, particularly voting, that are a bit vague in the general governance doc.

Also made a few changes to other docs. The title of the person who chairs the Core Team keeps changing in my mind as the duties get laid out. I'm assuming we'll take a final pass at all this when the docs are done.

### CODE REVIEW

**Review by ChrisMaddock — APPROVED** [review]
Everything here looks good to me.

**Comment by CharliePoole** [comment]
@rprouse Can you take a look at this?

**Comment by rprouse** [comment]
Looks good. The only possible gap I see is what to do if the chair cannot get a core team member's vote in a reasonable amount of time. Should we apply the 72 hour rule there too or a bit longer because they are important decisions?

**Review by rprouse — APPROVED** [review]

**Comment by CharliePoole** [comment]
My original idea was that the Chair would just decide in such a case. But as written, with five members, you only have to get three to approve in order to pass something, so I didn't bother with that. I'm working on the premise that anything not stated in advance will be invented on the spot. 😄 

But if you have some language we could add it.

**Comment by rprouse** [comment]
I think we can invent it on the spot. NUnit has been going for ages already and hasn't run into any serious issues that I know of 😄 

Feel free to merge when ready.

**Pull request merged**
