### PR TITLE
Updated Core Team

### PR DESCRIPTION
**Pull request by jnm2**
Added myself.

### CODE REVIEW

**Comment by ChrisMaddock** [comment]
> "The initial composition of the Core Team is"

Maybe change this line to 'current' too? Otherwise I don't think there's a problem here. 😄

**Comment by jnm2** [comment]
Good point. 😄

**Review by ChrisMaddock — APPROVED** [review]
I don't think there's anything controversial here...merging. 👍

**Comment by CharliePoole** [comment]
The intent of the document was to describe how the core team was initially created... bootstrapped that is. I saw a need for a document describing the actual membership - a very short one. obviously, but I was waiting for the core team to see the need and create it.

If you make that list a part of the main governance doc, then you have to repeatedly update that doc. Maybe you want a separate doc that lists the dates of adding and removing team members over time OR just one that shows current status. This is analogous to the way we don't list projects in the governance doc.

Anyway, I don't feel strongly about this one way or the other and it can be changed if it proves necessary. I do think it might be useful to have __both__ the initial composition and current composition. Otherwise, as some of us leave, you won't have any indication of how the team was created in the first place.

**Comment by jnm2** [comment]
I like the idea of moving it to a separate history doc.

**Pull request merged**
